
- name: Update all
  hosts: localhost
  vars:
    network_id: L_828099381482770866
    serial_number: QBSB-D5ZD-9CXT
  gather_facts: false
  tasks:
    - name: networks_appliance_traffic_shaping_rules
      cisco.meraki.networks_appliance_traffic_shaping_rules:
        state: present
        defaultRulesEnabled: true
        networkId: L_828099381482775374
        rules:
          - definitions:
              - type: host
                value: google.com
              - type: port
                value: '9090'
              - type: ipRange
                value: 192.1.0.0
              - type: ipRange
                value: 192.1.0.0/16
              - type: ipRange
                value: 10.1.0.0/16:80
              - type: localNet
                value: 192.168.0.0/16
            dscpTagValue: 0
            perClientBandwidthLimits:
              bandwidthLimits:
                limitDown: 2048
                limitUp: 2048
              settings: custom
            priority: normal